MaleFashion/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('blog/', include('posts.urls', namespace='posts')),
    path('profile/', include('users.urls', namespace='profile')),
    path('products/', include('products.urls', namespace='products'))

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auth/urls.py
from django.urls import path, include

from auth.views import password_changed

urlpatterns = [
    path('password/change/done/', password_changed),
    path('', include('registration.backends.default.urls'))
]

pages/urls.py
from django.urls import path

from pages.views import ContactCreateView, HomeTemplateView, AboutTemplateView


app_name = 'pages'
urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('contact/', ContactCreateView.as_view(), name='contact'),



]

posts/urls.py
from django.urls import path

from posts.views import PostsListView, PostDetailView, CommentCreateView

app_name='posts'
urlpatterns = [
    path('', PostsListView.as_view(), name='list'),
    path('<int:pk>/comment/', CommentCreateView.as_view(), name='comment'),
    path('<int:pk>/', PostDetailView.as_view(), name='detail')
]

products/urls.py
from django.urls import path

from products.views import ProductListView, ProductDetailView, WishListListView, add_wishlist, add_to_cart

app_name='products'

urlpatterns = [
    path('',ProductListView.as_view(), name='list'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('wishlist', WishListListView.as_view(), name='wishlist'),
    path('wishlist/<int:pk>/', add_wishlist, name='add-wishlist'),
    path('cart/<int:pk>/', add_to_cart, name='add-to-cart')
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Male-Fashion | Template</title>


    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
        rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    {% block extra_css %}{% endblock %}
</head>

<body>


   {% include 'layouts/header.html' %}

{% block content %}{% endblock %}

    {% include 'layouts/footer.html' %}


<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form action="{% url 'products:list' %}"class="search-model-form">
            <input name="q" type="text" id="search-input" placeholder="Search here">
        </form>
    </div>

</div>



    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    {% block extra_js %} {% endblock %}
</body>

</html>

templates/layouts/footer.html
{% load static %}
<footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__logo">
                            <a href="#"><img src="{% static 'img/footer-logo.png' %}" alt=""></a>
                        </div>
                        <p>The customer is at the heart of our unique business model, which includes design.</p>
                        <a href="#"><img src="{% static 'img/payment.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Clothing Store</a></li>
                            <li><a href="#">Trending Shoes</a></li>
                            <li><a href="#">Accessories</a></li>
                            <li><a href="#">Sale</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2 col-md-3 col-sm-6">
                    <div class="footer__widget">
                        <h6>Shopping</h6>
                        <ul>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Payment Methods</a></li>
                            <li><a href="#">Delivary</a></li>
                            <li><a href="#">Return & Exchanges</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                    <div class="footer__widget">
                        <h6>NewLetter</h6>
                        <div class="footer__newslatter">
                            <p>Be the first to know about new arrivals, look books, sales & promos!</p>
                            <form action="#">
                                <input type="text" placeholder="Your email">
                                <button type="submit"><span class="icon_mail_alt"></span></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="footer__copyright__text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright ©
                            <script>
                                document.write(new Date().getFullYear());
                            </script>2020
                            All rights reserved | This template is made with <i class="fa fa-heart-o"
                                aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        </p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>

templates/layouts/header.html
{% load static %}
{% load my_tags %}
<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
{#    <div class="offcanvas__option">#}
{#        <div class="offcanvas__links">#}
{#            {% if request.user.is_authenticated %}#}
{#                <a href="#">Proifle</a>#}
{#                <a href="#">History</a>#}
{#                <a href="{% url 'auth_logout' %}">Log out</a>#}
{#            {% else %}#}
{#                <a href="{% url 'auth_login' %}">Sign in</a>#}
{#            {% endif %}#}
{#        </div>#}
{##}
{#    </div>#}
    <div class="offcanvas__nav__option">
        <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
        <a href="#"><img src="{% static 'img/icon/cart.png' %}" alt=""> <span>0</span></a>
        <div class="price">$0.00</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
        <p>Free shipping, 30-day return or refund guarantee.</p>
    </div>
</div>

<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p>Free shipping, 30-day return or refund guarantee.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if request.user.is_authenticated %}
                                <a href="{% url 'auth_logout' %}">Log out</a>
                                <a href="{% url 'profile:home' %}">Profile</a>
                                <a href="#">History</a>
                            {% else %}
                                <a href="{% url 'auth_login' %}">Sign in</a>
                            {% endif %}
                        </div>
                        <div class="header__top__hover">
                            <span>Usd <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>EN</li>
                                <li>RU</li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="./index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li {% if request.path == '/' %}class="active"{% endif %}><a
                                href="{% url 'pages:home' %}">Home</a></li>
                        <li {% if request.path == '/products/' %}class="active"{% endif %}><a
                                href="{% url 'products:list' %}">Product</a></li>
                        <li><a href="#">Pages</a>
                        <li {% if request.path == '/blog/' %}class="active"{% endif %}><a href="{% url 'posts:list' %}">Blog</a>
                        <li {% if request.path == '/about/' %}class="active"{% endif %}><a
                                href="{% url 'pages:about' %}">About</a>
                        <li {% if request.path == '/contact/' %}class="active"{% endif %}><a
                                href="{% url 'pages:contact' %}">Contact</a>


                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
                    <a href="{% url 'products:wishlist' %}"><img src="{% static 'img/icon/heart.png' %}" alt=""></a>
                    <a href="#">
                        <img src="{% static 'img/icon/cart.png' %}" alt="">
                        <span>{% cart_count request %}</span>
                    </a>
                    <div class="price">${% cart_price request %}</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>

templates/layouts/product_block.html
{% load my_tags %}
{% load static %}
<div class="product__item sale">
    <div class="product__item__pic set-bg" data-setbg="{{ product.image.url }}">
        {% if product.is_discount %}

            <span class="label">Sale</span>
        {% endif %}
        {% if product.is_new %}
            <span class="label mt-4">New</span>
        {% endif %}
        <ul class="product__hover">
            <li>
                <a href="{% url 'products:add-wishlist' pk=product.pk %}?next={{ request.path }}?{{ request.GET.urlencode }}">
                    {% if product|in_wishlist:request %}
                    <img src="{% static 'img/icon/heartr.png' %}" alt="">
                    {% else %}
                    <img src="{% static 'img/icon/heart.png' %}" alt="">
                    {% endif %}
                </a>
            </li>
            <li><a href="#"><img src="{% static 'img/icon/compare.png' %}" alt="">
                <span>Compare</span></a>
            </li>
            <li><a href="{% url 'products:detail' pk=product.pk %}"><img src="{% static 'img/icon/search.png' %}"
                                                                         alt=""></a>
            </li>
        </ul>
    </div>
    <div class="product__item__text">
        <h6>{{ product.title }}</h6>
        <a href="{% url 'products:add-to-cart' pk=product.pk %}?next{{ request.path }}?{{ request.GET.urlencode }}" class="add-cart">
            {% if product|in_cart:request %}-Remove From Cart{% else %}+Add To Cart{% endif %}
        </a>
        <div class="rating">
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
            <i class="fa fa-star-o"></i>
        </div>
        <h5>${{ product.real_price }}
            {% if product.is_discount %}
                <strike class="small">{{ product.price }}</strike>
            {% endif %}
        </h5>
        <div class="product__color__select">
            {% for color in colors %}
                <label style="background:{{ color.code }}">

                    <input type="radio" onclick="addUrlParameter('color', '{{ color.pk }}')">
                </label>
            {% endfor %}

        </div>
    </div>
</div>

templates/layouts/shop_filter.html
{#{% load my_tags %}#}
{% block extra_css %}
    <style>
    a:hover {
        cursor: pointer;
    }

    </style>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ion-rangeslider/2.3.1/css/ion.rangeSlider.min.css"/>


{% endblock %}

<div class="col-lg-3">
    <div class="shop__sidebar">
        <div class="shop__sidebar__search">
            <form action="#">
                <input value="{{ request.GET.q }}" name="q" type="text" placeholder="Search...">
                <button type="submit"><span class="icon_search"></span></button>
            </form>
        </div>
        <div class="shop__sidebar__accordion">
            <div class="accordion" id="accordionExample">
             <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                    </div>
                    <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__price">

                             <input type="text" class="js-range-slider" name="my_range" value="" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseOne">Categories</a>
                    </div>
                    <div id="collapseOne" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__categories">
                                <ul class="nice-scroll">
                                    {% for category in categories %}
                                        <li>
                                            <a {% if request.GET.cat == category.pk|stringformat:'i' %}style="color: black"{% endif %}
                                               onclick="addUrlParameter('cat', '{{ category.pk }}')">{{ category.title }}</a></li>
                                    {% endfor %}


                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseSix">Tags</a>
                    </div>
                    <div id="collapseSix" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__tags">
                                {% for tag in tags %}
                                    <a {% if request.GET.tag == tag.pk|stringformat:'i' %}style="color:white;background-color:#111"{% endif %}
                                       onclick="addUrlParameter('tag', '{{ tag.pk }}')">{{ tag.title }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseTwo">Branding</a>
                    </div>
                    <div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__brand">
                                <ul>
                                    {% for brand in brands %}
                                        <li>
                                            <a {% if request.GET.brand == brand.pk|stringformat:'i' %}style="color: black"{% endif %}
                                               onclick="addUrlParameter('brand', '{{ brand.pk }}')">{{ brand.title }}</a></li>
                                    {% endfor %}

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseFour">Size</a>
                    </div>
                    <div id="collapseFour" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__size">
                                {% for size in sizes %}
                                <label>{{ size.title }}
                                    <input onclick="addUrlParameter('size', '{{ size.pk }}')" type="radio">
                                </label>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-heading">
                        <a data-toggle="collapse" data-target="#collapseFive">Colors</a>
                    </div>
                    <div id="collapseFive" class="collapse show" data-parent="#accordionExample">
                        <div class="card-body">
                            <div class="shop__sidebar__color">
                                {% for color in colors %}
                                <label style="background:{{ color.code }}">

                                    <input type="radio" onclick="addUrlParameter('color', '{{ color.pk }}')">
                                </label>
                                {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>